---
# Zsh with Prezto module
# Complete zsh shell environment with Prezto framework

# Core zsh dependencies
homebrew_packages:
  - zsh
  - zsh-history-substring-search

# Prezto framework â€” cloned automatically during install
git_repositories:
  - repo: "https://github.com/sorin-ionescu/prezto.git"
    dest: "~/.zprezto"
    version: "master"
    recursive: true

# Stow directories for zsh configs
stow_dirs:
  - zsh

# Files that should be merged with other modules
mergeable_files:
  - ".zshrc"
  - ".zshenv"
  - ".zpreztorc"
